---

- name: The deprecated versions of docker is not installed
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Dependent packages are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    update_cache: yes

- name: Official Docker GPG Key is added
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Docker repository is added
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

- name: Docker is installed
  apt:
    name: '{{ docker.package_name }}'
    update_cache: yes
