---

- name: The deprecated versions of docker is not installed
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Dependent packages are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    update_cache: yes

- name: Dependent packages on Ubuntu 14 are installed
  include_tasks: install_dependencies_for_ubuntu_14.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "14"

- name: Official Docker GPG Key is added
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Docker repository is added
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"

- name: Docker is installed
  apt:
    name: '{{ docker_package_name }}'
    update_cache: yes

- name: The docker service is configurated
  service:
    name: docker
    state: '{{ docker_service_state }}'
